### ISSUE TITLE
Share widgets on blog posts do not work.

### ISSUE THREAD

**Issue by ocdtrekkie** [jparyani/GhostSS#1]
Incomplete URLs are ending up in the share widget. As the non-clean URL probably shouldn't be shared out though, a new field where we can set the public URL may be required to fix this properly.

**Comment by jparyani** [comment]
As you surmised, this is a tough problem. I don't want to force the user to set the public URL explicitly, unless we have to. I'm going to try and replace the share buttons with javascript equivalents that fill in the current location. Does that sound workable to you?

**Comment by ocdtrekkie** [comment]
That sounds like it would do the trick.

**Comment by jparyani** [comment]
I've uploaded a fix. It's pretty hacky, in that it relies on certain classes being defined by the themes (see bed58a3860d861f356307a2fe31ce2b1395cd9b2), but I've made sure that this does work for all the current themes. I'll have to make sure any new themes added also follow this convention.

You can install by going to https://alpha.sandstorm.io/install/5af69dda6595827b895bb5d45f74371a. Update going to the app list in a bit.
