### ISSUE TITLE
"Connect to your domain" not working

### ISSUE THREAD

**Issue by sharpedavid** [jparyani/GhostSS#17]
I realize this is probably my fault, but I'm hoping you can spot my mistake. I'm having trouble pointing my http://sharpe.link domain to my Ghost blog hosted on Sandstorm Oasis.

When I click "Connect to your domain", I see the following instructions:

> To set up your domain to point at your published site, add the following DNS records to your domain. Replace host.example.com with your site's hostname.
> 
> host.example.com IN CNAME ulb63hm3tw8orec36o8r.oasis.sandstorm.io
> sandstorm-www.host.example.com IN TXT ulb63hm3tw8orec36o8r 

I'm unfamiliar with DNS, CNAME, etc., so I got Namecheap's tech support to help me create these records:

![image](https://cloud.githubusercontent.com/assets/1767127/12805715/3475587a-cab3-11e5-8e71-a16a1b444e20.png)

It's been a couple of hours, but www.sharpe.link still shows the following message:

> Error looking up DNS TXT records for host "www.sharpe.link": queryTxt ENOTFOUND
> 
> This Sandstorm server's main interface is at: https://oasis.sandstorm.io
> 
> If you were trying to connect this address to a Sandstorm app hosted at this server,
> you either have not set your DNS TXT records correctly or the DNS cache has not
> updated yet (may take a while).
> 
> If you are the server admin and want to use this address as the main interface,
> edit /opt/sandstorm/sandstorm.conf, modify the BASE_URL setting, and restart.
> 
> If you got here after trying to log in via OAuth (e.g. through Github or Google),
> the problem is probably that the OAuth callback URL was set wrong. You need to
> update it through the respective login provider's management console.

Can you spot what I've done wrong? I have a vague idea of what the CNAME and TXT records are doing, but not enough to spot the problem.

**Comment by sharpedavid** [comment]
Nevermind. Maybe I just needed to follow the Sandstorm instructions and not use Namecheap's help, because it's working now with just these records:

![image](https://cloud.githubusercontent.com/assets/1767127/12827855/95b48240-cb36-11e5-8f6a-e7a258f7934e.png)

I will close this issue immediately, but if you're reading this maybe you can answer this question: What is the TXT record for? I see that I can also access my blog at https://ulb63hm3tw8orec36o8r.oasis.sandstorm.io/, so why wouldn't I just create a CNAME record to point at that?

**Comment by paulproteus** [comment]
Glad you got this solved. The TXT record allows Sandstorm to know which grain you are attempting to connect to this server. The CNAME in theory contains that information, but that level of metadata gets washed away by CloudFlare.
