### ISSUE TITLE
Can't change default author name

### ISSUE THREAD

**Issue by ocdtrekkie** [jparyani/GhostSS#2]
If you try and change your profile name from "Sandstorm" to your own name, it fails to save because you didn't specify a valid email address. There is no email address field on the page. Since your profile name is the post author, the display name of the default user needs to be able to be edited.

**Comment by jparyani** [comment]
New spk is up at https://sandstorm.io/apps/ that fixes this. By default, it will put your Sandstorm name in there, but you're free to change it to anything you want, and it won't revert it.
