### ISSUE TITLE
disable the "Users" section

### ISSUE THREAD

**Issue by geofft** [jparyani/GhostSS#8]
#5 would be fantastic but in the interim, so long as multiple users don't work (and sending email definitely doesn't work), it'd be nice for that UI not to show up.

**Comment by jparyani** [comment]
I'm going to leave the Users section in because it's the only place you can change the Author's name (which shows up in various places). I removed the "New User" button since that makes no sense under Sandstorm.

Fixed in 9f1c0df522faae6af14095a8e80b8bc36dcecf2b

**Comment by jparyani** [comment]
Thanks for reporting!
